$ GCC ATARI.C/DEFINE=(BASIC,ATARI_LIBRARY="""object""")
$ GCC MONITOR.C
$ GCC CPU.C
$ GCC ATARI_CUSTOM.C/DEFINE=BASIC
$ GCC ATARI_H_DEVICE.C
$ GCC ATARI_SIO.C
$ GCC ATARI_BASIC.C
$ LINK/EXECUTABLE=ATARI800.EXE ATARI,MONITOR,CPU,ATARI_CUSTOM,ATARI_H_DEVICE,ATARI_SIO,ATARI_BASIC,SYS$INPUT/OPT
GNU_CC:[000000]LIBGCC/LIB
SYS$SHARE:VAXCRTL.EXE/SHARE
