all:
	@echo There are several different Makefiles for all supported architectures:
	@echo
	@echo For UNIX type \"cp Makefile.unix Makefile\"
	@echo For Linux-ia32 type \"cp Makefile.linux Makefile\"
	@echo For Amiga copy Makefile.amiga to Makefile
	@echo For MS-DOS/DJGPP type \"copy Makefile.dos Makefile\"
	@echo For Atari Falcon/TT/clones type \"cp Makefile.falcon Makefile\"
	@echo
	@echo After that you can type \"make\" again.
